  version: 2.1
  jobs:
    A:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command
    B:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    C:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    D:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command     
    E:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    F:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command   
    G:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    H:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    I:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
  workflows:
    version: 2
    AAAAAA:
      jobs:
        - A
        - B
        - C
            requires:
              - A
        - D
            requires:
              - A
              - B
        - E
            requires:
              - A
        - F
            requires:
              - C
        - G
            requires:
              - D
        - H
            requires:
              - E
              - B
         - I
            requires:
              - E