  version: 2.1
  jobs:
    PA:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command
    PB:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PC:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PD:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command     
    PE:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PF:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command   
    PG:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PH:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    PI:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
  workflows:
    version: 2
    AAAAAA:
      jobs:
        - PA
        - PB
        - PC:
            requires:
              - PA
        - PD:
            requires:
              - PA
              - PB
        - PE:
            requires:
              - PA
        - PF:
            requires:
              - PC
        - PG:
            requires:
              - PD
        - PH:
            requires:
              - PE
              - PB
        - PI:
            requires:
              - PE