  version: 2.1
  jobs:
    BUILD_A:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command
    BUILD_B:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    acceptance_test_2:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    acceptance_test_3:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command     
    acceptance_test_4:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
    deploy:
      docker: 
        - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
      steps:
        - run: echo "hello world" # run the `echo` command  
 
  workflows:
    version: 2
    AAAAAA:
      jobs:
        - BUILD_A
        - BUILD_B:
            requires:
              - BUILD_A
        - acceptance_test_2:
            requires:
              - BUILD_A
        - acceptance_test_3:
            requires:
              - BUILD_A
        - acceptance_test_4:
            requires:
              - BUILD_A
        - deploy:
            requires:
              - BUILD_B
              - acceptance_test_2
              - acceptance_test_3
              - acceptance_test_4